# Site settings
title: Allysa Fontillas
description: My Data Portfolio.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Allysa Fontillas
user_description: Driven Data Analytics student with a passion for problem-solving through insightful data analysis. Eager to apply academic training and analytical skills to drive business results and foster organizational growth in a data analyst position.
user_title: Data Analyst
email: allysa.fontillas@gmail.com
github_username:  Afontillas817

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
